spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/egtdigital?createDatabaseIfNotExist=true
    username: user
    password: secret

  jpa:
    properties:
      hibernate:
        generate_statistics: true
    database-platform: org.hibernate.dialect.MySQL8Dialect
    hibernate:
      ddl-auto: update
    show-sql: true

scheduling:
    fixedRate: 3600000 # 1 hour in milliseconds

fixerIo:
  accessKey: b1b53fb06f300fa95a8a1feeb98506f2
