version: '3.1'

services:
  mysql:
    container_name: mysql
    image: mysql:8.1
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: secret
      MYSQL_USER: user
      MYSQL_PASSWORD: secret
      MYSQL_DATABASE: egtdigital
    volumes:
      - mysql_volume:/var/lib/mysql
    ports:
      - "3306:3306"
  redis:
    image: redis:6.0.7
    container_name: redis
    restart: always
    volumes:
      - redis_volume:/data
    ports:
      - 6379:6379
  redis_insight:
    image: redislabs/redisinsight:1.14.0
    container_name: redis_insight
    restart: always
    ports:
      - 8001:8001
    volumes:
      - redis_insight_volume:/db

volumes:
  mysql_volume:
  redis_volume:
  redis_insight_volume: